server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp
    username: root
    password: Kishore#9900
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#springdoc:
#  swagger-ui:
#    enabled: true
#  api-docs:
#    enabled: true

#debug: true // will log debug entries
logging:
  level:
    com:
      movie: debug

    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG


